/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Arena(props) {
  const { nodes, materials } = useGLTF("/models/arena.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Plane-003"].geometry}
        material={materials["Material.001"]}
        rotation={[0, 0.02, 0]}
        scale={0.0038}
      />
    </group>
  );
}

useGLTF.preload("/models/arena.glb");