/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Coliseo(props) {
  const { nodes, materials } = useGLTF("/models/coliseo2.glb");
  return (
    <group {...props} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10064_colosseum_v1_Iteration0"].geometry}
        material={materials["10064_colosseum"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}


useGLTF.preload("/models/coliseo2.glb");
