/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Land(props) {
  const { nodes, materials } = useGLTF('/models/Land.glb');

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_001_tree_001_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-10, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_000_tree_000_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/*<mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_001_Cube_000_Fence.geometry}
        material={materials.Fence}
        rotation={[-Math.PI / 2, 0, 0]}
      />
     <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_003_Room_000_Roof_002.geometry}
        material={materials.Roof_002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_003_Room_000_house_002.geometry}
        material={materials.house_002}
        rotation={[-Math.PI / 2, 0, 0]}
  />*
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_003_Room_000_Window_aligment.geometry}
        material={materials.Window_aligment}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_003_Room_000_Window.geometry}
        material={materials.Window}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roof_003_Room_000_Door.geometry}
        material={materials.Door}
        rotation={[-Math.PI / 2, 0, 0]}
  />
  <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Topper_Topper.geometry}
        material={materials.Topper}
        rotation={[-Math.PI / 2, 0, 0]}
      />*/}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-20, -1, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-20, -1, 10]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-30, 0, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-30, 0, 10]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_024_Icosphere_039_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_013_Icosphere_038_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_013_Icosphere_038_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_012_Icosphere_037_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_012_Icosphere_037_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_023_Icosphere_036_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_023_Icosphere_036_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_022_Icosphere_035_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_022_Icosphere_035_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_021_Icosphere_034_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_021_Icosphere_034_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_020_Icosphere_033_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_020_Icosphere_033_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_011_Icosphere_032_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_011_Icosphere_032_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_010_Icosphere_031_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_010_Icosphere_031_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_019_Icosphere_030_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_019_Icosphere_030_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_018_Icosphere_029_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_018_Icosphere_029_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_017_Icosphere_028_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_017_Icosphere_028_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_016_Icosphere_027_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_016_Icosphere_027_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_009_Icosphere_026_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_009_Icosphere_026_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_008_Icosphere_025_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_008_Icosphere_025_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_015_Icosphere_024_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_015_Icosphere_024_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_014_Icosphere_023_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_014_Icosphere_023_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_007_Icosphere_022_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_007_Icosphere_022_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_006_Icosphere_021_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_006_Icosphere_021_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_013_Icosphere_020_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_013_Icosphere_020_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_012_Icosphere_019_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_012_Icosphere_019_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_011_Icosphere_018_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_011_Icosphere_018_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_010_Icosphere_017_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_010_Icosphere_017_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_005_Icosphere_016_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_005_Icosphere_016_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_004_Icosphere_015_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_004_Icosphere_015_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_009_Icosphere_014_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_009_Icosphere_014_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_008_Icosphere_013_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_008_Icosphere_013_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_007_Icosphere_012_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_007_Icosphere_012_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_006_Icosphere_011_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_006_Icosphere_011_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_003_Icosphere_010_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_003_Icosphere_010_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_002_Icosphere_009_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_002_Icosphere_009_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_005_Icosphere_008_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, -2.7, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_005_Icosphere_008_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, -2.7, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_004_Icosphere_007_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_004_Icosphere_007_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_003_Icosphere_006_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_003_Icosphere_006_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_002_Icosphere_005_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_002_Icosphere_005_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_001_Icosphere_004_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-25, 1.5, 35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_001_Icosphere_004_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-25, 1.5, 35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_004_Mesh_001_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_004_Mesh_001_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_001_Icosphere_002_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_001_Icosphere_002_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/*<mesh
        castShadow
        receiveShadow
        geometry={nodes.Way_Cube_008_Door.geometry}
        material={materials.Door}
        rotation={[-Math.PI / 2, 0, 0]}
/>
<mesh
        castShadow
        receiveShadow
        geometry={nodes.Footpath_Cube_007_Foothpath.geometry}
        material={materials.Foothpath}
        rotation={[-Math.PI / 2, 0, 0]}
      />*/}

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_002_tree_002_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-5, 1, 20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_Icosphere_001_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2_Icosphere_001_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock_Cube_006_Rock.geometry}
        material={materials.Rock}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-12, 1, 45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape_001_Plane_002_water.geometry}
        material={materials.water}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-12, 1, 45]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_Icosphere_Leaf.geometry}
        material={materials.Leaf}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-30, 1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Leaf_Icosphere_Tree.geometry}
        material={materials.Tree}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[-30, 1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Road_Cube_001_Road.geometry}
        material={materials.Road}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape_Plane_Landscape.geometry}
        material={materials.Landscape}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/Land.glb');
