/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Panteon(props) {
  const { nodes, materials } = useGLTF("/models/panteon.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 8.09, 0]} rotation={[0, -0.07, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials.Stone_Walls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials.Plinths}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_2.geometry}
          material={materials.Doorway}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_3.geometry}
          material={materials.Doorway_Surround}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_4.geometry}
          material={materials.Columns}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_5.geometry}
          material={materials.Scrolls}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_6.geometry}
          material={materials.Architrave}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_7.geometry}
          material={materials.Roof_Tiles}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_8.geometry}
          material={materials.Pediment}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_9.geometry}
          material={materials.Base}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/panteon.glb");