/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PrimaPorta(props) {
  const { nodes, materials } = useGLTF("/models/primaporta.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.imagetostl_mesh0.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/primaporta.glb");